services:
  vehiculo-db:
    image: postgres:latest
    container_name: vehiculo-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: vehiculo_user
      POSTGRES_PASSWORD: vehiculo_password
      POSTGRES_DB: vehiculo_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vehiculo_user"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - vehiculo_db_data:/var/lib/postgresql/data
  sucursal-db:
    image: postgres:latest
    container_name: sucursal-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: sucursal_user
      POSTGRES_PASSWORD: sucursal_password
      POSTGRES_DB: sucursal_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sucursal_user"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - sucursal_db_data:/var/lib/postgresql/data
  stock-db:
    image: postgres:latest
    container_name: stock-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: stock_user
      POSTGRES_PASSWORD: stock_password
      POSTGRES_DB: stock_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stock_user" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - stock_db_data:/var/lib/postgresql/data
volumes:
  vehiculo_db_data:
  sucursal_db_data:
  stock_db_data: